name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Trigger Render Deployment
        env:
          SERVICE_ID: srv-ctkq9ta3esus73ear4u0
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/v1/services/$SERVICE_ID/deploys \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"branch":"main"}'

      - name: Set Render Environment Variables
        env:
          SERVICE_ID: srv-ctkq9ta3esus73ear4u0
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          curl -X PATCH https://api.render.com/v1/services/$SERVICE_ID/env-vars \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
                "envVars": [
                  {"key": "SPRING_DATA_MONGODB_URI", "value": "'"$MONGODB_URI"'"}
                ]
              }'
