name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger Render deployment
        run: |
          curl -X POST https://api.render.com/v1/services/{your-service-id}/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"branch":"main"}'

      - name: Set Render environment variables
        run: |
          curl -X PATCH https://api.render.com/v1/services/{your-service-id} \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{
                "envVars": [
                  {"key":"SPRING_DATA_MONGODB_URI", "value":"${{ secrets.MONGODB_URI }}"}
                ]
              }'
